### ISSUE TITLE
Create About Page Skeleton

### ISSUE THREAD

**Issue by rayreham** [rayreham/Assignment1#3]
Create bare HTML page of expected text

**Comment by janmarkusmilan** [comment]
Robin Hood
  
  
    
        
            
                
            
            
          
            
                
                    
                        Home
                    
                    
                        About(current)
                    
                
            
        
    
    

    
        
            
                
                    
                        
                            STAFF
                            Our team includes PhDs, attorneys, nonprofit leaders, government officials, and management experts. Also, musicians, actors, journalists, yoga instructors, ski bums, and chefs. We come from a variety of backgrounds, but we all share a common commitment to helping low-income New Yorkers escape poverty’s grasp.
                            
                                Directory 
                            
                        
                    
                    
                        
                            GOVERNANCE
                            So much of our ambition as an organization is thanks to our distinguished board. The dedication at the board level is unsurpassed, as evidenced by their personal and financial commitment: all administrative costs are underwritten by our board members so that 100% of your donation is used to save lives.
                            
                                Boards 
                            
                        
                    
                    
                        
                            CAREERS
                            A career at Robin Hood or one of our partner organizations requires a passion for taking on poverty in New York City: those who thrive in a demanding, fast-paced environment. Our team is creative, collaborative, and willing to do whatever it takes to get the job done. And we like to have fun while doing it.
                            
                                Join Us
